'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Readable } = require('node:stream');
const express = require('express');
const { createDiskAuth } = require('../server/disk-auth');
const { createDiskAPI } = require('../server/disk-api');
const { createTelegramDriveStore } = require('../server/telegram-drive');
const { createDiskOperations } = require('../server/disk-operations');

test('一次性协同邀请只开放受邀目录，撤销成员和关闭协同立即阻断访问与删除保护', async t => {
    const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'disk-collab-'));
    t.after(() => fs.rmSync(dataDir, { recursive: true, force: true }));
    const auth = createDiskAuth({ dataDir });
    const owner = auth.fromTelegram({ id: '101' }), guest = auth.fromTelegram({ id: '202' });
    const store = createTelegramDriveStore({ dataDir });
    store.createDirectory(owner.id, '共享/子目录', 20);
    store.createDirectory(owner.id, '私密', 20);
    const staged = store.begin({ owner, folderPath: '共享', files: [{ name: 'shared.txt', size: 1 }], maxDepth: 20 });
    await store.receive(staged.id, 0, Readable.from(['x']));
    const [file] = store.commit(staged.id, '-1001', [{ fileId: 'file-remote', messageId: 10 }]);
    const operations = createDiskOperations({ dataDir });
    const api = createDiskAPI({ dataDir, defaultStore: store, auth, operations, telegram: { remove: async () => {}, readPart: async () => Readable.from(['x']), upload: async () => [{ fileId:'new-remote', messageId:11, parts:[{ fileId:'new-remote', messageId:11, size:3 }] }] }, getDefaultBackend: () => ({ token: 'fake', channelId: '-1001' }), getIdentity: req => req.get('X-Test-User') === 'guest' ? guest : owner, setIdentity() {}, getOrigin: () => 'http://localhost', isMockRequest: () => true, maxDepth: () => 20 });
    t.after(() => api.close());
    const app = express(); app.use(express.json()); app.use('/drive', api.browser);
    const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
    t.after(() => new Promise(resolve => server.close(resolve)));
    const base = `http://127.0.0.1:${server.address().port}/drive`;
    const call = async (url, user = 'owner', method = 'GET', body) => {
        const response = await fetch(base + url, { method, headers: { 'X-Test-User': user, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
        return { status: response.status, data: await response.json() };
    };
    const invited = await call('/collaborations/invitations', 'owner', 'POST', { kind: 'directory', path: '共享' });
    assert.equal(invited.status, 201, JSON.stringify(invited.data));
    assert.match(invited.data.url, /\/disk-collab\//);
    const token = decodeURIComponent(invited.data.url.split('/').pop());
    const joined = await call('/collaborations/join', 'guest', 'POST', { token });
    assert.equal(joined.status, 200);
    assert.equal(joined.data.collaboration.path, '共享');
    assert.equal(joined.data.collaboration.invites, undefined);
    assert.equal((await call('/collaborations/join', 'guest', 'POST', { token })).status, 404);
    const scope = `/collaboration-scope/${joined.data.collaboration.id}`;
    const listing = await call(scope + '/list?path=%E5%85%B1%E4%BA%AB', 'guest');
    assert.equal(listing.status, 200); assert.equal(listing.data.files[0].id, file.id);
    assert.equal((await call(scope + '/list?path=%E7%A7%81%E5%AF%86', 'guest')).status, 403);
    assert.equal((await call(scope + '/uploads', 'guest', 'POST', { folderPath: '私密', files: [{ name: 'x', size: 1 }] })).status, 403);
    const replaced = await fetch(base + scope + '/files/' + file.id + '/repair', { method:'POST', headers:{ 'X-Test-User':'guest', 'Content-Type':'application/octet-stream', 'X-Disk-File-Size':'3', 'X-Disk-File-Type':'text/plain' }, body:Buffer.from('new') });
    assert.equal(replaced.status, 202);
    const replacementJob = (await replaced.json()).operation_id;
    for (let index = 0; index < 100 && operations.get(replacementJob, { userId: owner.id, diskSpace:'' })?.status !== 'completed'; index++) await new Promise(resolve => setTimeout(resolve, 5));
    assert.equal(operations.get(replacementJob, { userId: owner.id, diskSpace:'' })?.status, 'completed');
    assert.equal(store.get(owner.id, file.id).size, 3);
    const allowedUpload = await call(scope + '/uploads', 'guest', 'POST', { folderPath: '共享', files: [{ name: 'new.txt', size: 1 }] });
    assert.equal(allowedUpload.status, 201);
    assert.equal((await call(scope + `/uploads/${allowedUpload.data.uploadId}`, 'guest', 'DELETE')).status, 200);
    assert.equal((await call('/files/' + file.id, 'owner', 'DELETE')).status, 202);
    assert.equal((await call('/directories?path=%E5%85%B1%E4%BA%AB&recursive=true', 'owner', 'DELETE')).status, 403);
    const grantId = joined.data.collaboration.id;
    assert.equal((await call(`/collaborations/${grantId}/members/${guest.id}`, 'owner', 'DELETE')).status, 200);
    assert.equal((await call(scope + '/list', 'guest')).status, 404);
    assert.equal((await call(`/collaborations/${grantId}`, 'owner', 'DELETE')).status, 200);
    assert.equal((await call('/directories?path=%E5%85%B1%E4%BA%AB&recursive=true', 'owner', 'DELETE')).status, 202);
});
