'use strict';

const webext = globalThis.browser || globalThis.chrome;
const PERIODIC_ALARM = 'drop2tunnel-cookie-periodic';
const PAGE_ALARM = 'drop2tunnel-cookie-page';
const DEFAULTS = Object.freeze({
    enabled: false,
    servers: [],
    serverUrl: '',
    syncToken: '',
    intervalMinutes: 15,
    pageResyncMinutes: 30,
    lastSyncAt: 0,
    lastSnsOpenedAt: 0,
    lastYoutubeOpenedAt: 0,
    lastCookieHash: '',
    lastResult: '',
    lastError: ''
});
const SNS_PLATFORMS = Object.freeze([
    { id: 'youtube', label: 'YouTube / YT Music', domains: ['youtube.com'], login: /^(?:LOGIN_INFO|SID|HSID|SSID|APISID|SAPISID|__Secure-[13]P(?:SID|APISID)(?:TS|CC)?)$/ },
    { id: 'tiktok', label: 'TikTok', domains: ['tiktok.com'], login: /^(?:sessionid|sessionid_ss|sid_tt|sid_guard)$/i },
    { id: 'facebook', label: 'Facebook', domains: ['facebook.com'], login: /^(?:c_user|xs)$/i },
    { id: 'instagram', label: 'Instagram', domains: ['instagram.com'], login: /^(?:sessionid|ds_user_id)$/i },
    { id: 'thread', label: 'Threads', domains: ['threads.com', 'threads.net', 'instagram.com'], login: /^(?:sessionid|ds_user_id)$/i },
    { id: 'line', label: 'LINE', domains: ['line.me'] },
    { id: 'twitter', label: 'Twitter', domains: ['twitter.com', 'x.com'], login: /^auth_token$/i },
    { id: 'x', label: 'X', domains: ['x.com', 'twitter.com'], login: /^auth_token$/i }
]);
let activeSync = null;

async function getSettings() {
    const settings = { ...DEFAULTS, ...await webext.storage.local.get(DEFAULTS) };
    const hasServers = Array.isArray(settings.servers) && settings.servers.length > 0;
    if (!hasServers && settings.serverUrl && settings.syncToken) {
        settings.servers = [{
            id: crypto.randomUUID(),
            serverUrl: normalizeServerUrl(settings.serverUrl),
            syncToken: String(settings.syncToken).trim()
        }];
        await webext.storage.local.set({ servers: settings.servers, lastCookieHash: '', lastSyncAt: 0, lastResult: '', lastError: '' });
        await webext.storage.local.remove(['serverUrl', 'syncToken']);
    }
    settings.servers = (Array.isArray(settings.servers) ? settings.servers : [])
        .filter(server => server?.serverUrl && server?.syncToken);
    return settings;
}

function normalizeServerUrl(value) {
    const url = new URL(String(value || '').trim());
    if (!['http:', 'https:'].includes(url.protocol)) throw new Error('服务器地址必须使用 HTTP 或 HTTPS');
    return url.origin;
}

function normalizeSyncToken(value) {
    const matches = String(value || '').split(/[^A-Za-z0-9_-]+/).filter(part => part.length === 43);
    if (matches.length !== 1) throw new Error('同步密钥格式无效，请重新复制管理页生成的密钥');
    return matches[0];
}

function makeNetscapeCookies(cookies) {
    const rows = cookies
        .sort((a, b) => `${a.domain}\t${a.path}\t${a.name}`.localeCompare(`${b.domain}\t${b.path}\t${b.name}`))
        .map(cookie => {
            const baseDomain = String(cookie.domain || '').replace(/^#HttpOnly_/, '');
            const domain = cookie.httpOnly ? `#HttpOnly_${baseDomain}` : baseDomain;
            const includeSubdomains = cookie.hostOnly ? 'FALSE' : 'TRUE';
            const secure = cookie.secure ? 'TRUE' : 'FALSE';
            const expires = Math.max(0, Math.floor(Number(cookie.expirationDate) || 0));
            const name = String(cookie.name || '').replace(/[\t\r\n]/g, '');
            const value = String(cookie.value || '').replace(/[\t\r\n]/g, '');
            return [domain, includeSubdomains, cookie.path || '/', secure, expires, name, value].join('\t');
        });
    return `# Netscape HTTP Cookie File\n# Generated by Drop2Tunnel administrator extension.\n${rows.join('\n')}\n`;
}

function isSupportedCookieDomain(value) {
    const host = String(value || '').replace(/^\./, '').toLowerCase();
    return SNS_PLATFORMS.some(platform => platform.domains.some(domain => host === domain || host.endsWith(`.${domain}`)));
}

async function collectSnsCookieFiles() {
    const files = [];
    const skipped = [];
    for (const platform of SNS_PLATFORMS) {
        const groups = await Promise.all(platform.domains.map(domain => webext.cookies.getAll({ domain })));
        const cookies = [...new Map(groups.flat().map(cookie => [
            `${cookie.storeId || ''}\t${cookie.domain}\t${cookie.path}\t${cookie.name}`,
            cookie
        ])).values()];
        if (!cookies.length || (platform.login && !cookies.some(cookie => platform.login.test(cookie.name || '')))) {
            skipped.push(platform.label);
            continue;
        }
        files.push({ platform: platform.id, content: makeNetscapeCookies(cookies) });
    }
    if (!files.length) throw new Error('当前浏览器未发现任何受支持 SNS 平台的可用登录 Cookie');
    return { files, skipped };
}

async function sha256(value) {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value));
    return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');
}

async function syncServer(server, files) {
    const serverUrl = normalizeServerUrl(server.serverUrl);
    const syncToken = normalizeSyncToken(server.syncToken);
    const response = await fetch(`${serverUrl}/api/sns-cookie-sync`, {
        method: 'POST',
        cache: 'no-store',
        headers: {
            'Authorization': `Bearer ${syncToken}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ platforms: Object.fromEntries(files.map(file => [file.platform, file.content])) })
    });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(`${serverUrl}：${result.error || `HTTP ${response.status}`}`);
    return { serverUrl, ...result };
}

async function syncSnsCookies(trigger, force = false) {
    if (activeSync) return activeSync;
    activeSync = (async () => {
        const settings = await getSettings();
        if (!settings.enabled && !force) return { skipped: true, reason: 'disabled' };
        if (!settings.servers.length) throw new Error('请先添加至少一个 Drop2Tunnel 服务器');

        const { files, skipped } = await collectSnsCookieFiles();
        const cookieHash = await sha256(files.map(file => `${file.platform}\n${file.content}`).join('\n'));
        const minRepeatMs = Math.max(5, Number(settings.intervalMinutes) || 15) * 45000;
        if (!force && cookieHash === settings.lastCookieHash && Date.now() - settings.lastSyncAt < minRepeatMs) {
            return { skipped: true, reason: 'unchanged' };
        }

        const settled = await Promise.allSettled(settings.servers.map(server => syncServer(server, files)));
        const results = settled.filter(item => item.status === 'fulfilled').map(item => item.value);
        const failures = settled.filter(item => item.status === 'rejected').map(item => item.reason?.message || '未知错误');
        if (failures.length) {
            throw new Error(`已同步 ${results.length}/${settings.servers.length} 台服务器；${failures.join('；')}`);
        }
        const now = Date.now();
        const totalBytes = files.reduce((sum, file) => sum + new TextEncoder().encode(file.content).byteLength, 0);
        await webext.storage.local.set({
            lastSyncAt: now,
            lastCookieHash: cookieHash,
            lastResult: `${new Date(now).toLocaleString()} · ${trigger} · ${results.length} 台服务器 · ${files.length} 个平台 · ${(totalBytes / 1024).toFixed(1)} KB${skipped.length ? ` · 跳过：${skipped.join('、')}` : ''}`,
            lastError: ''
        });
        return { ok: true, servers: results, platforms: files.map(file => file.platform), skipped };
    })().catch(async error => {
        await webext.storage.local.set({ lastError: `${new Date().toLocaleString()} · ${error.message}` });
        throw error;
    }).finally(() => {
        activeSync = null;
    });
    return activeSync;
}

async function configureAlarm() {
    const settings = await getSettings();
    await webext.alarms.clear(PERIODIC_ALARM);
    if (settings.enabled) {
        const periodInMinutes = Math.max(5, Number(settings.intervalMinutes) || 15);
        webext.alarms.create(PERIODIC_ALARM, { delayInMinutes: 1, periodInMinutes });
    }
}

webext.runtime.onInstalled.addListener(() => configureAlarm());
webext.runtime.onStartup.addListener(() => configureAlarm());
webext.storage.onChanged.addListener((changes, area) => {
    if (area === 'local' && (changes.enabled || changes.intervalMinutes)) configureAlarm();
});

webext.alarms.onAlarm.addListener(alarm => {
    if (alarm.name === PERIODIC_ALARM) syncSnsCookies('定时同步').catch(() => {});
    if (alarm.name === PAGE_ALARM) syncSnsCookies('打开 SNS 页面后同步').catch(() => {});
});

webext.cookies.onChanged.addListener(change => {
    if (!isSupportedCookieDomain(change.cookie?.domain)) return;
    webext.alarms.create(PAGE_ALARM, { delayInMinutes: 1 });
});

webext.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type === 'get-settings') {
        getSettings()
            .then(settings => sendResponse({ ok: true, settings }))
            .catch(error => sendResponse({ ok: false, error: error.message }));
        return true;
    }
    if (message?.type === 'sns-opened' || message?.type === 'youtube-opened') {
        getSettings().then(settings => {
            const now = Date.now();
            const threshold = Math.max(5, Number(settings.pageResyncMinutes) || 30) * 60000;
            const lastOpenedAt = settings.lastSnsOpenedAt || settings.lastYoutubeOpenedAt;
            webext.storage.local.set({ lastSnsOpenedAt: now });
            if (settings.enabled && now - lastOpenedAt >= threshold) {
                webext.alarms.create(PAGE_ALARM, { delayInMinutes: 0.05 });
            }
        });
        return;
    }
    if (message?.type === 'sync-now') {
        syncSnsCookies('手动立即同步', true)
            .then(result => sendResponse({ ok: true, result }))
            .catch(error => sendResponse({ ok: false, error: error.message }));
        return true;
    }
    if (message?.type === 'configure-alarm') {
        configureAlarm().then(() => sendResponse({ ok: true }));
        return true;
    }
});
