function normalizeLanguageCode(value = '') {
    const raw = String(value || '').toLowerCase();
    if (raw.startsWith('zh') && (raw.includes('hant') || raw.includes('tw') || raw.includes('hk'))) return 'zh-Hant';
    if (raw.startsWith('zh')) return 'zh-Hans';
    if (raw.startsWith('ja')) return 'ja';
    if (raw.startsWith('fr')) return 'fr';
    if (raw.startsWith('ru')) return 'ru';
    if (raw.startsWith('es')) return 'es';
    if (raw.startsWith('it')) return 'it';
    if (raw.startsWith('fa')) return 'fa';
    if (raw.startsWith('ko')) return 'ko';
    if (raw.startsWith('ms')) return 'ms';
    if (raw.startsWith('id')) return 'id';
    if (raw.startsWith('vi')) return 'vi';
    if (raw.startsWith('km')) return 'km';
    if (raw.startsWith('my') || raw.startsWith('bur')) return 'my';
    if (raw.startsWith('th')) return 'th';
    if (raw.startsWith('en')) return 'en';
    return 'zh-Hans';
}

const TG = {
    '没有找到这个隧道暗号，请确认 5 位暗号是否正确。': {
        'zh-Hant': '找不到這個隧道暗號，請確認 5 位暗號是否正確。', en: 'I could not find that tunnel code. Please check the 5-character code.', ja: 'そのトンネルコードが見つかりません。5文字のコードを確認してください。', fr: 'Code de tunnel introuvable. Vérifiez le code à 5 caractères.', ru: 'Код туннеля не найден. Проверьте 5-символьный код.', es: 'No encontré ese código de túnel. Comprueba el código de 5 caracteres.', it: 'Non trovo questo codice tunnel. Controlla il codice di 5 caratteri.', fa: 'این کد تونل پیدا نشد. لطفاً کد ۵ نویسه‌ای را بررسی کنید.', ko: '해당 터널 코드를 찾을 수 없습니다. 5자리 코드를 확인하세요.', ms: 'Kod terowong itu tidak ditemui. Semak kod 5 aksara.', id: 'Kode tunnel tidak ditemukan. Periksa kode 5 karakter.', vi: 'Không tìm thấy mã đường hầm đó. Vui lòng kiểm tra mã 5 ký tự.', km: 'រកមិនឃើញលេខសម្ងាត់ផ្លូវរូងនេះទេ។ សូមពិនិត្យលេខ 5 តួអក្សរ។', my: 'ထိုတန်နယ်ကုဒ်ကို မတွေ့ပါ။ စာလုံး ၅ လုံးကုဒ်ကို စစ်ဆေးပါ။', th: 'ไม่พบรหัสอุโมงค์นี้ โปรดตรวจสอบรหัส 5 ตัวอักษร'
    },
    '媒体合辑处理失败，请稍后重试。': { 'zh-Hant': '媒體合輯處理失敗，請稍後重試。', en: 'Media collection processing failed. Please try again later.', ja: 'メディア合輯の処理に失敗しました。後でもう一度お試しください。', fr: 'Le traitement de la collection média a échoué. Réessayez plus tard.', ru: 'Не удалось обработать медиаподборку. Повторите позже.', es: 'No se pudo procesar la colección multimedia. Inténtalo más tarde.', it: 'Elaborazione raccolta multimediale non riuscita. Riprova più tardi.', fa: 'پردازش مجموعه رسانه ناموفق بود. بعداً دوباره تلاش کنید.', ko: '미디어 모음 처리에 실패했습니다. 나중에 다시 시도하세요.', ms: 'Pemprosesan koleksi media gagal. Cuba lagi kemudian.', id: 'Pemrosesan koleksi media gagal. Coba lagi nanti.', vi: 'Xử lý bộ sưu tập media thất bại. Vui lòng thử lại sau.', km: 'ដំណើរការបណ្តុំមេឌៀបរាជ័យ។ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។', my: 'မီဒီယာစုစည်းမှု လုပ်ဆောင်မှု မအောင်မြင်ပါ။ နောက်မှ ထပ်ကြိုးစားပါ။', th: 'ประมวลผลชุดสื่อไม่สำเร็จ โปรดลองอีกครั้งภายหลัง' },
    '已放弃待发送内容。': { 'zh-Hant': '已放棄待傳送內容。', en: 'Pending content was cancelled.', ja: '送信待ちの内容を破棄しました。', fr: 'Le contenu en attente a été annulé.', ru: 'Ожидающее содержимое отменено.', es: 'Se canceló el contenido pendiente.', it: 'Contenuto in sospeso annullato.', fa: 'محتوای در انتظار لغو شد.', ko: '대기 중인 내용이 취소되었습니다.', ms: 'Kandungan menunggu telah dibatalkan.', id: 'Konten tertunda dibatalkan.', vi: 'Nội dung đang chờ đã bị hủy.', km: 'បានបោះបង់មាតិកាដែលកំពុងរង់ចាំផ្ញើ។', my: 'ပို့ရန်စောင့်နေသော အကြောင်းအရာကို ပယ်ဖျက်ပြီးပါပြီ။', th: 'ยกเลิกเนื้อหาที่รอส่งแล้ว' },
    '已离开隧道中转模式。': { 'zh-Hant': '已離開隧道中轉模式。', en: 'Tunnel relay mode has been left.', ja: 'トンネル中継モードを終了しました。', fr: 'Mode relais du tunnel quitté.', ru: 'Режим ретрансляции туннеля отключён.', es: 'Has salido del modo retransmisión del túnel.', it: 'Modalità inoltro tunnel uscita.', fa: 'از حالت رله تونل خارج شدید.', ko: '터널 중계 모드를 나갔습니다.', ms: 'Mod geganti terowong telah ditinggalkan.', id: 'Mode relay tunnel telah ditinggalkan.', vi: 'Đã rời chế độ chuyển tiếp đường hầm.', km: 'បានចាកចេញពីរបៀបបញ្ជូនផ្លូវរូង។', my: 'တန်နယ် relay မုဒ်မှ ထွက်ပြီးပါပြီ။', th: 'ออกจากโหมดส่งต่ออุโมงค์แล้ว' },
    '当前不在隧道中转模式。': { 'zh-Hant': '目前不在隧道中轉模式。', en: 'You are not currently in tunnel relay mode.', ja: '現在トンネル中継モードではありません。', fr: 'Vous n’êtes pas en mode relais du tunnel.', ru: 'Сейчас вы не в режиме ретрансляции туннеля.', es: 'Ahora no estás en modo retransmisión del túnel.', it: 'Non sei in modalità inoltro tunnel.', fa: 'در حال حاضر در حالت رله تونل نیستید.', ko: '현재 터널 중계 모드가 아닙니다.', ms: 'Anda tidak berada dalam mod geganti terowong.', id: 'Anda tidak sedang dalam mode relay tunnel.', vi: 'Bạn hiện không ở chế độ chuyển tiếp đường hầm.', km: 'អ្នកមិនស្ថិតក្នុងរបៀបបញ្ជូនផ្លូវរូងទេ។', my: 'လက်ရှိ တန်နယ် relay မုဒ်တွင် မရှိပါ။', th: 'ขณะนี้ไม่ได้อยู่ในโหมดส่งต่ออุโมงค์' },
    '请输入 5 位隧道暗号。': { 'zh-Hant': '請輸入 5 位隧道暗號。', en: 'Please enter the 5-character tunnel code.', ja: '5文字のトンネルコードを入力してください。', fr: 'Saisissez le code de tunnel à 5 caractères.', ru: 'Введите 5-символьный код туннеля.', es: 'Introduce el código de túnel de 5 caracteres.', it: 'Inserisci il codice tunnel di 5 caratteri.', fa: 'کد ۵ نویسه‌ای تونل را وارد کنید.', ko: '5자리 터널 코드를 입력하세요.', ms: 'Masukkan kod terowong 5 aksara.', id: 'Masukkan kode tunnel 5 karakter.', vi: 'Nhập mã đường hầm 5 ký tự.', km: 'សូមបញ្ចូលលេខសម្ងាត់ផ្លូវរូង 5 តួអក្សរ។', my: 'စာလုံး ၅ လုံး တန်နယ်ကုဒ် ထည့်ပါ။', th: 'โปรดป้อนรหัสอุโมงค์ 5 ตัวอักษร' },
    '输入 5 位隧道暗号': { 'zh-Hant': '輸入 5 位隧道暗號', en: 'Enter the 5-character tunnel code', ja: '5文字のトンネルコードを入力', fr: 'Entrez le code de tunnel à 5 caractères', ru: 'Введите 5-символьный код туннеля', es: 'Introduce el código de túnel de 5 caracteres', it: 'Inserisci il codice tunnel di 5 caratteri', fa: 'کد ۵ نویسه‌ای تونل را وارد کنید', ko: '5자리 터널 코드 입력', ms: 'Masukkan kod terowong 5 aksara', id: 'Masukkan kode tunnel 5 karakter', vi: 'Nhập mã đường hầm 5 ký tự', km: 'បញ្ចូលលេខសម្ងាត់ផ្លូវរូង 5 តួអក្សរ', my: 'စာလုံး ၅ လုံး တန်နယ်ကုဒ် ထည့်ပါ', th: 'ป้อนรหัสอุโมงค์ 5 ตัวอักษร' },
    '此前绑定的隧道已失效，已自动退出中转模式。请重新使用 /tunnel 进入有效隧道。': { 'zh-Hant': '先前綁定的隧道已失效，已自動退出中轉模式。請重新使用 /tunnel 進入有效隧道。', en: 'The previously bound tunnel is no longer valid, so relay mode was exited automatically. Use /tunnel again to enter a valid tunnel.', ja: '以前バインドしたトンネルは無効になったため、中継モードを自動終了しました。有効なトンネルに入るには /tunnel を再度使用してください。', fr: 'Le tunnel lié n’est plus valide ; le mode relais a été quitté automatiquement. Utilisez /tunnel pour entrer dans un tunnel valide.', ru: 'Ранее привязанный туннель недействителен, режим ретрансляции отключён. Используйте /tunnel снова.', es: 'El túnel vinculado ya no es válido; se salió del modo retransmisión. Usa /tunnel otra vez.', it: 'Il tunnel associato non è più valido; la modalità inoltro è stata chiusa. Usa di nuovo /tunnel.', fa: 'تونل قبلی دیگر معتبر نیست و حالت رله خودکار بسته شد. دوباره از /tunnel استفاده کنید.', ko: '이전에 연결한 터널이 유효하지 않아 중계 모드가 자동 종료되었습니다. /tunnel로 다시 연결하세요.', ms: 'Terowong terikat sebelum ini tidak sah; mod geganti ditamatkan automatik. Guna /tunnel semula.', id: 'Tunnel terikat sebelumnya tidak valid; mode relay keluar otomatis. Gunakan /tunnel lagi.', vi: 'Đường hầm đã liên kết không còn hợp lệ nên đã tự thoát chế độ chuyển tiếp. Hãy dùng lại /tunnel.', km: 'ផ្លូវរូងដែលបានភ្ជាប់ពីមុនមិនមានសុពលភាពទេ ដូច្នេះបានចេញពីរបៀបបញ្ជូនដោយស្វ័យប្រវត្តិ។ ប្រើ /tunnel ម្តងទៀត។', my: 'ယခင်ချိတ်ထားသော တန်နယ် မမှန်တော့သဖြင့် relay မုဒ်မှ အလိုအလျောက် ထွက်ပြီးပါပြီ။ /tunnel ကို ထပ်သုံးပါ။', th: 'อุโมงค์ที่ผูกไว้ก่อนหน้าไม่ถูกต้องแล้ว จึงออกจากโหมดส่งต่ออัตโนมัติ ใช้ /tunnel ใหม่อีกครั้ง' },
    '待发送内容已处理完成。': { 'zh-Hant': '待傳送內容已處理完成。', en: 'Pending content has been processed.', ja: '送信待ちの内容を処理しました。', fr: 'Le contenu en attente a été traité.', ru: 'Ожидающее содержимое обработано.', es: 'El contenido pendiente se procesó.', it: 'Contenuto in sospeso elaborato.', fa: 'محتوای در انتظار پردازش شد.', ko: '대기 중인 내용이 처리되었습니다.', ms: 'Kandungan menunggu telah diproses.', id: 'Konten tertunda telah diproses.', vi: 'Nội dung đang chờ đã được xử lý.', km: 'មាតិកាដែលកំពុងរង់ចាំត្រូវបានដំណើរការរួច។', my: 'ပို့ရန်စောင့်နေသော အကြောင်းအရာ လုပ်ဆောင်ပြီးပါပြီ။', th: 'ประมวลผลเนื้อหาที่รอส่งแล้ว' },
    '所发内容的备注文字中没有找到 5 位隧道暗号，请提供给我；也可以点击“放弃发送”。': { 'zh-Hant': '在所發內容的備註中找不到 5 位隧道暗號，請提供給我；也可以點選「放棄傳送」。', en: 'I could not find a 5-character tunnel code in the caption. Please send it, or tap “Cancel sending”.', ja: 'キャプションに5文字のトンネルコードが見つかりません。送信するか、「送信をキャンセル」を押してください。', fr: 'Aucun code de tunnel à 5 caractères dans la légende. Envoyez-le ou touchez « Annuler l’envoi ».', ru: 'В подписи нет 5-символьного кода туннеля. Отправьте его или нажмите «Отменить отправку».', es: 'No encontré un código de túnel de 5 caracteres en el texto. Envíalo o toca “Cancelar envío”.', it: 'Non trovo un codice tunnel di 5 caratteri nella didascalia. Invialo o tocca “Annulla invio”.', fa: 'در توضیح، کد ۵ نویسه‌ای تونل پیدا نشد. آن را بفرستید یا «لغو ارسال» را بزنید.', ko: '캡션에서 5자리 터널 코드를 찾지 못했습니다. 코드를 보내거나 “보내기 취소”를 누르세요.', ms: 'Kod terowong 5 aksara tidak ditemui dalam kapsyen. Hantar kod atau ketik “Batal hantar”.', id: 'Kode tunnel 5 karakter tidak ditemukan di keterangan. Kirim kodenya atau ketuk “Batalkan pengiriman”.', vi: 'Không tìm thấy mã đường hầm 5 ký tự trong chú thích. Hãy gửi mã hoặc bấm “Hủy gửi”.', km: 'រកមិនឃើញលេខសម្ងាត់ផ្លូវរូង 5 តួអក្សរក្នុងចំណាំទេ។ សូមផ្ញើវា ឬចុច “បោះបង់ការផ្ញើ”។', my: 'စာတန်းတွင် စာလုံး ၅ လုံး တန်နယ်ကုဒ် မတွေ့ပါ။ ကုဒ်ပို့ပါ သို့မဟုတ် “ပို့ခြင်းပယ်ဖျက်” ကိုနှိပ်ပါ။', th: 'ไม่พบรหัสอุโมงค์ 5 ตัวอักษรในคำบรรยาย โปรดส่งรหัส หรือแตะ “ยกเลิกการส่ง”' }
};

function translateExact(text, lang) {
    if (!text || lang === 'zh-Hans') return text;
    const entry = TG[text];
    return entry?.[lang] || entry?.en || text;
}

function translateTelegramText(text, langCode = 'zh-Hans') {
    const lang = normalizeLanguageCode(langCode);
    let translated = translateExact(text, lang);
    if (translated !== text) return translated;
    if (lang === 'zh-Hans') return text;
    let match = /^当前处于 ([A-Z0-9]{5}) 隧道中转模式，直接发送任何内容，将转发到此隧道。$/.exec(text);
    if (match) return ({
        'zh-Hant': `目前處於 ${match[1]} 隧道中轉模式，直接傳送任何內容都會轉發到此隧道。`, en: `Tunnel relay mode is active for ${match[1]}. Anything you send will be forwarded to this tunnel.`, ja: `${match[1]} のトンネル中継モードです。送信した内容はこのトンネルへ転送されます。`, fr: `Le mode relais est actif pour le tunnel ${match[1]}. Tout ce que vous envoyez sera transféré à ce tunnel.`, ru: `Включён режим ретрансляции для туннеля ${match[1]}. Всё отправленное будет переслано туда.`, es: `Modo retransmisión activo para el túnel ${match[1]}. Todo lo que envíes se reenviará a este túnel.`, it: `Modalità inoltro attiva per il tunnel ${match[1]}. Tutto ciò che invii sarà inoltrato a questo tunnel.`, fa: `حالت رله برای تونل ${match[1]} فعال است. هر چیزی بفرستید به این تونل منتقل می‌شود.`, ko: `${match[1]} 터널 중계 모드입니다. 보내는 모든 내용이 이 터널로 전달됩니다.`, ms: `Mod geganti aktif untuk terowong ${match[1]}. Apa-apa yang dihantar akan dimajukan ke terowong ini.`, id: `Mode relay aktif untuk tunnel ${match[1]}. Apa pun yang Anda kirim akan diteruskan ke tunnel ini.`, vi: `Chế độ chuyển tiếp đang bật cho đường hầm ${match[1]}. Mọi nội dung bạn gửi sẽ được chuyển tiếp vào đó.`, km: `របៀបបញ្ជូនសកម្មសម្រាប់ផ្លូវរូង ${match[1]}។ អ្វីៗដែលអ្នកផ្ញើនឹងត្រូវបញ្ជូនទៅផ្លូវរូងនេះ។`, my: `${match[1]} တန်နယ်အတွက် relay မုဒ် ဖွင့်ထားသည်။ သင်ပို့သမျှကို ထိုတန်နယ်သို့ ပို့မည်။`, th: `โหมดส่งต่อเปิดอยู่สำหรับอุโมงค์ ${match[1]} ทุกอย่างที่ส่งจะถูกส่งต่อเข้าอุโมงค์นี้` }[lang] || text);
    match = /^文件太大，当前 Telegram bot 接收上限是 (\d+)MB。$/.exec(text);
    if (match) return ({ en: `The file is too large. The current Telegram bot receive limit is ${match[1]} MB.`, 'zh-Hant': `檔案太大，目前 Telegram bot 接收上限是 ${match[1]}MB。`, ja: `ファイルが大きすぎます。現在の Telegram bot 受信上限は ${match[1]}MB です。`, fr: `Le fichier est trop volumineux. La limite actuelle du bot Telegram est de ${match[1]} Mo.`, ru: `Файл слишком большой. Текущий лимит Telegram bot: ${match[1]} МБ.`, es: `El archivo es demasiado grande. El límite actual del bot de Telegram es ${match[1]} MB.`, it: `Il file è troppo grande. Il limite attuale del bot Telegram è ${match[1]} MB.`, fa: `فایل بیش از حد بزرگ است. سقف دریافت فعلی ربات تلگرام ${match[1]} مگابایت است.`, ko: `파일이 너무 큽니다. 현재 Telegram bot 수신 한도는 ${match[1]}MB입니다.`, ms: `Fail terlalu besar. Had penerimaan Telegram bot ialah ${match[1]} MB.`, id: `File terlalu besar. Batas penerimaan bot Telegram saat ini ${match[1]} MB.`, vi: `Tệp quá lớn. Giới hạn nhận hiện tại của Telegram bot là ${match[1]} MB.`, km: `ឯកសារធំពេក។ កម្រិតទទួលបច្ចុប្បន្នរបស់ Telegram bot គឺ ${match[1]}MB។`, my: `ဖိုင်ကြီးလွန်းသည်။ လက်ရှိ Telegram bot လက်ခံနိုင်သောကန့်သတ်ချက်မှာ ${match[1]}MB ဖြစ်သည်။`, th: `ไฟล์ใหญ่เกินไป ขีดจำกัดรับของ Telegram bot ตอนนี้คือ ${match[1]}MB` }[lang] || text);
    match = /^已发送到隧道 ([A-Z0-9]{5})(?::|：)?(.*)$/.exec(text);
    if (match) return ({ en: `Sent to tunnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, 'zh-Hant': `已傳送到隧道 ${match[1]}${match[2] ? `：${match[2].trim()}` : '。'}`, ja: `トンネル ${match[1]} に送信しました${match[2] ? `：${match[2].trim()}` : '。'}`, fr: `Envoyé au tunnel ${match[1]}${match[2] ? ` : ${match[2].trim()}` : '.'}`, ru: `Отправлено в туннель ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, es: `Enviado al túnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, it: `Inviato al tunnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, fa: `به تونل ${match[1]} ارسال شد${match[2] ? `: ${match[2].trim()}` : '.'}`, ko: `${match[1]} 터널로 보냈습니다${match[2] ? `: ${match[2].trim()}` : '.'}`, ms: `Dihantar ke terowong ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, id: `Dikirim ke tunnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, vi: `Đã gửi tới đường hầm ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, km: `បានផ្ញើទៅផ្លូវរូង ${match[1]}${match[2] ? `: ${match[2].trim()}` : '។'}`, my: `${match[1]} တန်နယ်သို့ ပို့ပြီးပါပြီ${match[2] ? `: ${match[2].trim()}` : '။'}`, th: `ส่งไปยังอุโมงค์ ${match[1]} แล้ว${match[2] ? `: ${match[2].trim()}` : ''}` }[lang] || text);
    match = /^已将 (\d+) 个媒体文件以合辑发送到隧道 ([A-Z0-9]{5})。$/.exec(text);
    if (match) return ({ en: `Sent ${match[1]} media files as a collection to tunnel ${match[2]}.`, 'zh-Hant': `已將 ${match[1]} 個媒體檔案以合輯傳送到隧道 ${match[2]}。`, ja: `${match[1]} 個のメディアファイルを合輯としてトンネル ${match[2]} に送信しました。`, fr: `${match[1]} fichiers média ont été envoyés comme collection au tunnel ${match[2]}.`, ru: `${match[1]} медиафайлов отправлены подборкой в туннель ${match[2]}.`, es: `Se enviaron ${match[1]} archivos multimedia como colección al túnel ${match[2]}.`, it: `${match[1]} file multimediali inviati come raccolta al tunnel ${match[2]}.`, fa: `${match[1]} فایل رسانه‌ای به‌صورت مجموعه به تونل ${match[2]} ارسال شد.`, ko: `미디어 파일 ${match[1]}개를 모음으로 ${match[2]} 터널에 보냈습니다.`, ms: `${match[1]} fail media dihantar sebagai koleksi ke terowong ${match[2]}.`, id: `${match[1]} file media dikirim sebagai koleksi ke tunnel ${match[2]}.`, vi: `Đã gửi ${match[1]} tệp media dưới dạng bộ sưu tập tới đường hầm ${match[2]}.`, km: `បានផ្ញើឯកសារមេឌៀ ${match[1]} ជាបណ្តុំទៅផ្លូវរូង ${match[2]}។`, my: `မီဒီယာဖိုင် ${match[1]} ခုကို စုစည်းမှုအဖြစ် ${match[2]} တန်နယ်သို့ ပို့ပြီးပါပြီ။`, th: `ส่งไฟล์สื่อ ${match[1]} ไฟล์เป็นชุดไปยังอุโมงค์ ${match[2]} แล้ว` }[lang] || text);
    return text;
}

module.exports = { normalizeLanguageCode, translateTelegramText };
