function normalizeLanguageCode(value = '') {
    const raw = String(value || '').toLowerCase();
    if (raw.startsWith('zh') && (raw.includes('hant') || raw.includes('tw') || raw.includes('hk'))) return 'zh-Hant';
    if (raw.startsWith('zh')) return 'zh-Hans';
    if (raw.startsWith('ja')) return 'ja';
    if (raw.startsWith('fr')) return 'fr';
    if (raw.startsWith('ru')) return 'ru';
    if (raw.startsWith('es')) return 'es';
    if (raw.startsWith('it')) return 'it';
    if (raw.startsWith('fa')) return 'fa';
    if (raw.startsWith('ko')) return 'ko';
    if (raw.startsWith('ms')) return 'ms';
    if (raw.startsWith('id')) return 'id';
    if (raw.startsWith('vi')) return 'vi';
    if (raw.startsWith('km')) return 'km';
    if (raw.startsWith('my')) return 'my';
    if (raw.startsWith('th')) return 'th';
    if (raw.startsWith('en')) return 'en';
    return 'zh-Hans';
}

const TG = {
    '没有找到这个隧道暗号，请确认 5 位暗号是否正确。': {
        'zh-Hant': '找不到這個隧道暗號，請確認 5 位暗號是否正確。', en: 'I could not find that tunnel code. Please check the 5-character code.', ja: 'そのトンネルコードが見つかりません。5文字のコードを確認してください。', fr: 'Code de tunnel introuvable. Vérifiez le code à 5 caractères.', ru: 'Код туннеля не найден. Проверьте 5-символьный код.', es: 'No encontré ese código de túnel. Comprueba el código de 5 caracteres.', it: 'Non trovo questo codice tunnel. Controlla il codice di 5 caratteri.', fa: 'این کد تونل پیدا نشد. لطفاً کد ۵ نویسه‌ای را بررسی کنید.', ko: '해당 터널 코드를 찾을 수 없습니다. 5자리 코드를 확인하세요.', ms: 'Kod terowong itu tidak ditemui. Semak kod 5 aksara.', id: 'Kode tunnel tidak ditemukan. Periksa kode 5 karakter.', vi: 'Không tìm thấy mã đường hầm đó. Vui lòng kiểm tra mã 5 ký tự.', km: 'រកមិនឃើញលេខសម្ងាត់ផ្លូវរូងនេះទេ។ សូមពិនិត្យលេខ 5 តួអក្សរ។', my: 'ထိုတန်နယ်ကုဒ်ကို မတွေ့ပါ။ စာလုံး ၅ လုံးကုဒ်ကို စစ်ဆေးပါ။', th: 'ไม่พบรหัสอุโมงค์นี้ โปรดตรวจสอบรหัส 5 ตัวอักษร'
    },
    '媒体合辑处理失败，请稍后重试。': { 'zh-Hant': '媒體合輯處理失敗，請稍後重試。', en: 'Media collection processing failed. Please try again later.', ja: 'メディア合輯の処理に失敗しました。後でもう一度お試しください。', fr: 'Le traitement de la collection média a échoué. Réessayez plus tard.', ru: 'Не удалось обработать медиаподборку. Повторите позже.', es: 'No se pudo procesar la colección multimedia. Inténtalo más tarde.', it: 'Elaborazione raccolta multimediale non riuscita. Riprova più tardi.', fa: 'پردازش مجموعه رسانه ناموفق بود. بعداً دوباره تلاش کنید.', ko: '미디어 모음 처리에 실패했습니다. 나중에 다시 시도하세요.', ms: 'Pemprosesan koleksi media gagal. Cuba lagi kemudian.', id: 'Pemrosesan koleksi media gagal. Coba lagi nanti.', vi: 'Xử lý bộ sưu tập media thất bại. Vui lòng thử lại sau.', km: 'ដំណើរការបណ្តុំមេឌៀបរាជ័យ។ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។', my: 'မီဒီယာစုစည်းမှု လုပ်ဆောင်မှု မအောင်မြင်ပါ။ နောက်မှ ထပ်ကြိုးစားပါ။', th: 'ประมวลผลชุดสื่อไม่สำเร็จ โปรดลองอีกครั้งภายหลัง' },
    '已放弃待发送内容。': { 'zh-Hant': '已放棄待傳送內容。', en: 'Pending content was cancelled.', ja: '送信待ちの内容を破棄しました。', fr: 'Le contenu en attente a été annulé.', ru: 'Ожидающее содержимое отменено.', es: 'Se canceló el contenido pendiente.', it: 'Contenuto in sospeso annullato.', fa: 'محتوای در انتظار لغو شد.', ko: '대기 중인 내용이 취소되었습니다.', ms: 'Kandungan menunggu telah dibatalkan.', id: 'Konten tertunda dibatalkan.', vi: 'Nội dung đang chờ đã bị hủy.', km: 'បានបោះបង់មាតិកាដែលកំពុងរង់ចាំផ្ញើ។', my: 'ပို့ရန်စောင့်နေသော အကြောင်းအရာကို ပယ်ဖျက်ပြီးပါပြီ။', th: 'ยกเลิกเนื้อหาที่รอส่งแล้ว' },
    '已离开隧道中转模式。': { 'zh-Hant': '已離開隧道中轉模式。', en: 'Tunnel relay mode has been left.', ja: 'トンネル中継モードを終了しました。', fr: 'Mode relais du tunnel quitté.', ru: 'Режим ретрансляции туннеля отключён.', es: 'Has salido del modo retransmisión del túnel.', it: 'Modalità inoltro tunnel uscita.', fa: 'از حالت رله تونل خارج شدید.', ko: '터널 중계 모드를 나갔습니다.', ms: 'Mod geganti terowong telah ditinggalkan.', id: 'Mode relay tunnel telah ditinggalkan.', vi: 'Đã rời chế độ chuyển tiếp đường hầm.', km: 'បានចាកចេញពីរបៀបបញ្ជូនផ្លូវរូង។', my: 'တန်နယ် relay မုဒ်မှ ထွက်ပြီးပါပြီ။', th: 'ออกจากโหมดส่งต่ออุโมงค์แล้ว' },
    '当前不在隧道中转模式。': { 'zh-Hant': '目前不在隧道中轉模式。', en: 'You are not currently in tunnel relay mode.', ja: '現在トンネル中継モードではありません。', fr: 'Vous n’êtes pas en mode relais du tunnel.', ru: 'Сейчас вы не в режиме ретрансляции туннеля.', es: 'Ahora no estás en modo retransmisión del túnel.', it: 'Non sei in modalità inoltro tunnel.', fa: 'در حال حاضر در حالت رله تونل نیستید.', ko: '현재 터널 중계 모드가 아닙니다.', ms: 'Anda tidak berada dalam mod geganti terowong.', id: 'Anda tidak sedang dalam mode relay tunnel.', vi: 'Bạn hiện không ở chế độ chuyển tiếp đường hầm.', km: 'អ្នកមិនស្ថិតក្នុងរបៀបបញ្ជូនផ្លូវរូងទេ។', my: 'လက်ရှိ တန်နယ် relay မုဒ်တွင် မရှိပါ။', th: 'ขณะนี้ไม่ได้อยู่ในโหมดส่งต่ออุโมงค์' },
    '请输入 5 位隧道暗号。': { 'zh-Hant': '請輸入 5 位隧道暗號。', en: 'Please enter the 5-character tunnel code.', ja: '5文字のトンネルコードを入力してください。', fr: 'Saisissez le code de tunnel à 5 caractères.', ru: 'Введите 5-символьный код туннеля.', es: 'Introduce el código de túnel de 5 caracteres.', it: 'Inserisci il codice tunnel di 5 caratteri.', fa: 'کد ۵ نویسه‌ای تونل را وارد کنید.', ko: '5자리 터널 코드를 입력하세요.', ms: 'Masukkan kod terowong 5 aksara.', id: 'Masukkan kode tunnel 5 karakter.', vi: 'Nhập mã đường hầm 5 ký tự.', km: 'សូមបញ្ចូលលេខសម្ងាត់ផ្លូវរូង 5 តួអក្សរ។', my: 'စာလုံး ၅ လုံး တန်နယ်ကုဒ် ထည့်ပါ။', th: 'โปรดป้อนรหัสอุโมงค์ 5 ตัวอักษร' },
    '输入 5 位隧道暗号': { 'zh-Hant': '輸入 5 位隧道暗號', en: 'Enter the 5-character tunnel code', ja: '5文字のトンネルコードを入力', fr: 'Entrez le code de tunnel à 5 caractères', ru: 'Введите 5-символьный код туннеля', es: 'Introduce el código de túnel de 5 caracteres', it: 'Inserisci il codice tunnel di 5 caratteri', fa: 'کد ۵ نویسه‌ای تونل را وارد کنید', ko: '5자리 터널 코드 입력', ms: 'Masukkan kod terowong 5 aksara', id: 'Masukkan kode tunnel 5 karakter', vi: 'Nhập mã đường hầm 5 ký tự', km: 'បញ្ចូលលេខសម្ងាត់ផ្លូវរូង 5 តួអក្សរ', my: 'စာလုံး ၅ လုံး တန်နယ်ကုဒ် ထည့်ပါ', th: 'ป้อนรหัสอุโมงค์ 5 ตัวอักษร' },
    '此前绑定的隧道已失效，已自动退出中转模式。请重新使用 /tunnel 进入有效隧道。': { 'zh-Hant': '先前綁定的隧道已失效，已自動退出中轉模式。請重新使用 /tunnel 進入有效隧道。', en: 'The previously bound tunnel is no longer valid, so relay mode was exited automatically. Use /tunnel again to enter a valid tunnel.', ja: '以前バインドしたトンネルは無効になったため、中継モードを自動終了しました。有効なトンネルに入るには /tunnel を再度使用してください。', fr: 'Le tunnel lié n’est plus valide ; le mode relais a été quitté automatiquement. Utilisez /tunnel pour entrer dans un tunnel valide.', ru: 'Ранее привязанный туннель недействителен, режим ретрансляции отключён. Используйте /tunnel снова.', es: 'El túnel vinculado ya no es válido; se salió del modo retransmisión. Usa /tunnel otra vez.', it: 'Il tunnel associato non è più valido; la modalità inoltro è stata chiusa. Usa di nuovo /tunnel.', fa: 'تونل قبلی دیگر معتبر نیست و حالت رله خودکار بسته شد. دوباره از /tunnel استفاده کنید.', ko: '이전에 연결한 터널이 유효하지 않아 중계 모드가 자동 종료되었습니다. /tunnel로 다시 연결하세요.', ms: 'Terowong terikat sebelum ini tidak sah; mod geganti ditamatkan automatik. Guna /tunnel semula.', id: 'Tunnel terikat sebelumnya tidak valid; mode relay keluar otomatis. Gunakan /tunnel lagi.', vi: 'Đường hầm đã liên kết không còn hợp lệ nên đã tự thoát chế độ chuyển tiếp. Hãy dùng lại /tunnel.', km: 'ផ្លូវរូងដែលបានភ្ជាប់ពីមុនមិនមានសុពលភាពទេ ដូច្នេះបានចេញពីរបៀបបញ្ជូនដោយស្វ័យប្រវត្តិ។ ប្រើ /tunnel ម្តងទៀត។', my: 'ယခင်ချိတ်ထားသော တန်နယ် မမှန်တော့သဖြင့် relay မုဒ်မှ အလိုအလျောက် ထွက်ပြီးပါပြီ။ /tunnel ကို ထပ်သုံးပါ။', th: 'อุโมงค์ที่ผูกไว้ก่อนหน้าไม่ถูกต้องแล้ว จึงออกจากโหมดส่งต่ออัตโนมัติ ใช้ /tunnel ใหม่อีกครั้ง' },
    '待发送内容已处理完成。': { 'zh-Hant': '待傳送內容已處理完成。', en: 'Pending content has been processed.', ja: '送信待ちの内容を処理しました。', fr: 'Le contenu en attente a été traité.', ru: 'Ожидающее содержимое обработано.', es: 'El contenido pendiente se procesó.', it: 'Contenuto in sospeso elaborato.', fa: 'محتوای در انتظار پردازش شد.', ko: '대기 중인 내용이 처리되었습니다.', ms: 'Kandungan menunggu telah diproses.', id: 'Konten tertunda telah diproses.', vi: 'Nội dung đang chờ đã được xử lý.', km: 'មាតិកាដែលកំពុងរង់ចាំត្រូវបានដំណើរការរួច។', my: 'ပို့ရန်စောင့်နေသော အကြောင်းအရာ လုပ်ဆောင်ပြီးပါပြီ။', th: 'ประมวลผลเนื้อหาที่รอส่งแล้ว' },
    '所发内容的备注文字中没有找到 5 位隧道暗号，请提供给我；也可以点击“放弃发送”。': { 'zh-Hant': '在所發內容的備註中找不到 5 位隧道暗號，請提供給我；也可以點選「放棄傳送」。', en: 'I could not find a 5-character tunnel code in the caption. Please send it, or tap “Cancel sending”.', ja: 'キャプションに5文字のトンネルコードが見つかりません。送信するか、「送信をキャンセル」を押してください。', fr: 'Aucun code de tunnel à 5 caractères dans la légende. Envoyez-le ou touchez « Annuler l’envoi ».', ru: 'В подписи нет 5-символьного кода туннеля. Отправьте его или нажмите «Отменить отправку».', es: 'No encontré un código de túnel de 5 caracteres en el texto. Envíalo o toca “Cancelar envío”.', it: 'Non trovo un codice tunnel di 5 caratteri nella didascalia. Invialo o tocca “Annulla invio”.', fa: 'در توضیح، کد ۵ نویسه‌ای تونل پیدا نشد. آن را بفرستید یا «لغو ارسال» را بزنید.', ko: '캡션에서 5자리 터널 코드를 찾지 못했습니다. 코드를 보내거나 “보내기 취소”를 누르세요.', ms: 'Kod terowong 5 aksara tidak ditemui dalam kapsyen. Hantar kod atau ketik “Batal hantar”.', id: 'Kode tunnel 5 karakter tidak ditemukan di keterangan. Kirim kodenya atau ketuk “Batalkan pengiriman”.', vi: 'Không tìm thấy mã đường hầm 5 ký tự trong chú thích. Hãy gửi mã hoặc bấm “Hủy gửi”.', km: 'រកមិនឃើញលេខសម្ងាត់ផ្លូវរូង 5 តួអក្សរក្នុងចំណាំទេ។ សូមផ្ញើវា ឬចុច “បោះបង់ការផ្ញើ”។', my: 'စာတန်းတွင် စာလုံး ၅ လုံး တန်နယ်ကုဒ် မတွေ့ပါ။ ကုဒ်ပို့ပါ သို့မဟုတ် “ပို့ခြင်းပယ်ဖျက်” ကိုနှိပ်ပါ။', th: 'ไม่พบรหัสอุโมงค์ 5 ตัวอักษรในคำบรรยาย โปรดส่งรหัส หรือแตะ “ยกเลิกการส่ง”' }
};

const SERVER_LANGUAGES = ['zh-Hant', 'en', 'ja', 'fr', 'ru', 'es', 'it', 'ko', 'ms', 'id', 'vi', 'th', 'fa', 'km', 'my'];
const SERVER_ROWS = [
    ['请输入 5 位隧道暗号','請輸入 5 位隧道暗號','Please enter the 5-character tunnel code','5文字のトンネルコードを入力してください','Veuillez saisir le code de tunnel à 5 caractères','Введите 5-символьный код туннеля','Introduce el código de túnel de 5 caracteres','Inserisci il codice tunnel di 5 caratteri','5자리 터널 코드를 입력하세요','Sila masukkan kod terowong 5 aksara','Silakan masukkan kode tunnel 5 karakter','Vui lòng nhập mã đường hầm 5 ký tự','โปรดป้อนรหัสทันเนล 5 ตัวอักษร'],
    ['请求过于频繁，请稍后再试','請求過於頻繁，請稍後再試','Too many requests. Please try again later.','リクエストが多すぎます。後でもう一度お試しください。','Trop de requêtes. Réessayez plus tard.','Слишком много запросов. Повторите позже.','Demasiadas solicitudes. Inténtalo más tarde.','Troppe richieste. Riprova più tardi.','요청이 너무 많습니다. 나중에 다시 시도하세요.','Terlalu banyak permintaan. Cuba lagi kemudian.','Terlalu banyak permintaan. Coba lagi nanti.','Quá nhiều yêu cầu. Vui lòng thử lại sau.','มีคำขอมากเกินไป โปรดลองอีกครั้งภายหลัง'],
    ['请求过于频繁','請求過於頻繁','Too many requests','リクエストが多すぎます','Trop de requêtes','Слишком много запросов','Demasiadas solicitudes','Troppe richieste','요청이 너무 많습니다','Terlalu banyak permintaan','Terlalu banyak permintaan','Quá nhiều yêu cầu','มีคำขอมากเกินไป'],
    ['消息发送过于频繁','訊息傳送過於頻繁','Messages are being sent too quickly','メッセージの送信が速すぎます','Les messages sont envoyés trop rapidement','Сообщения отправляются слишком часто','Los mensajes se envían demasiado rápido','I messaggi vengono inviati troppo rapidamente','메시지를 너무 자주 보내고 있습니다','Mesej dihantar terlalu kerap','Pesan dikirim terlalu cepat','Tin nhắn được gửi quá nhanh','ส่งข้อความถี่เกินไป'],
    ['同步过于频繁','同步過於頻繁','Sync requests are too frequent','同期リクエストが多すぎます','Les synchronisations sont trop fréquentes','Слишком частые запросы синхронизации','Las solicitudes de sincronización son demasiado frecuentes','Le richieste di sincronizzazione sono troppo frequenti','동기화 요청이 너무 잦습니다','Permintaan segerak terlalu kerap','Permintaan sinkronisasi terlalu sering','Yêu cầu đồng bộ quá thường xuyên','คำขอซิงค์ถี่เกินไป'],
    ['无效的数据格式','資料格式無效','Invalid data format','データ形式が無効です','Format de données invalide','Недопустимый формат данных','Formato de datos no válido','Formato dati non valido','잘못된 데이터 형식입니다','Format data tidak sah','Format data tidak valid','Định dạng dữ liệu không hợp lệ','รูปแบบข้อมูลไม่ถูกต้อง'],
    ['无效的会话ID','工作階段ID無效','Invalid session ID','セッションIDが無効です','ID de session invalide','Недопустимый ID сеанса','ID de sesión no válido','ID sessione non valido','잘못된 세션 ID입니다','ID sesi tidak sah','ID sesi tidak valid','ID phiên không hợp lệ','รหัสเซสชันไม่ถูกต้อง'],
    ['无效的设备ID','裝置ID無效','Invalid device ID','デバイスIDが無効です','ID d’appareil invalide','Недопустимый ID устройства','ID de dispositivo no válido','ID dispositivo non valido','잘못된 기기 ID입니다','ID peranti tidak sah','ID perangkat tidak valid','ID thiết bị không hợp lệ','รหัสอุปกรณ์ไม่ถูกต้อง'],
    ['无效的设备名称','裝置名稱無效','Invalid device name','デバイス名が無効です','Nom d’appareil invalide','Недопустимое имя устройства','Nombre de dispositivo no válido','Nome dispositivo non valido','잘못된 기기 이름입니다','Nama peranti tidak sah','Nama perangkat tidak valid','Tên thiết bị không hợp lệ','ชื่ออุปกรณ์ไม่ถูกต้อง'],
    ['设备ID不匹配','裝置ID不相符','Device ID does not match','デバイスIDが一致しません','L’ID de l’appareil ne correspond pas','ID устройства не совпадает','El ID del dispositivo no coincide','L’ID dispositivo non corrisponde','기기 ID가 일치하지 않습니다','ID peranti tidak sepadan','ID perangkat tidak cocok','ID thiết bị không khớp','รหัสอุปกรณ์ไม่ตรงกัน'],
    ['服务器会话已满','伺服器工作階段已滿','The server has reached its session limit','サーバーのセッション数が上限に達しました','Le serveur a atteint sa limite de sessions','Достигнут лимит сеансов сервера','El servidor alcanzó el límite de sesiones','Il server ha raggiunto il limite di sessioni','서버 세션 한도에 도달했습니다','Pelayan telah mencapai had sesi','Server telah mencapai batas sesi','Máy chủ đã đạt giới hạn phiên','เซิร์ฟเวอร์ถึงขีดจำกัดเซสชันแล้ว'],
    ['会话设备数已满','工作階段裝置數已滿','This session has reached its device limit','このセッションはデバイス数の上限に達しました','Cette session a atteint sa limite d’appareils','Достигнут лимит устройств в сеансе','La sesión alcanzó el límite de dispositivos','La sessione ha raggiunto il limite di dispositivi','세션의 기기 한도에 도달했습니다','Sesi ini telah mencapai had peranti','Sesi ini telah mencapai batas perangkat','Phiên đã đạt giới hạn thiết bị','เซสชันนี้ถึงขีดจำกัดอุปกรณ์แล้ว'],
    ['会话文件数量已达上限','工作階段檔案數量已達上限','This session has reached its file limit','このセッションはファイル数の上限に達しました','Cette session a atteint sa limite de fichiers','Достигнут лимит файлов в сеансе','La sesión alcanzó el límite de archivos','La sessione ha raggiunto il limite di file','세션의 파일 한도에 도달했습니다','Sesi ini telah mencapai had fail','Sesi ini telah mencapai batas file','Phiên đã đạt giới hạn tệp','เซสชันนี้ถึงขีดจำกัดไฟล์แล้ว'],
    ['连接数超限','連線數超過上限','Connection limit exceeded','接続数の上限を超えました','Limite de connexions dépassée','Превышен лимит подключений','Se superó el límite de conexiones','Limite di connessioni superato','연결 한도를 초과했습니다','Had sambungan dilebihi','Batas koneksi terlampaui','Đã vượt giới hạn kết nối','เกินขีดจำกัดการเชื่อมต่อ'],
    ['服务器内部错误','伺服器內部錯誤','Internal server error','サーバー内部エラー','Erreur interne du serveur','Внутренняя ошибка сервера','Error interno del servidor','Errore interno del server','서버 내부 오류','Ralat dalaman pelayan','Kesalahan internal server','Lỗi máy chủ nội bộ','ข้อผิดพลาดภายในเซิร์ฟเวอร์'],
    ['短码应为 5 位字母或数字','短碼應為 5 位英文字母或數字','The short code must contain 5 letters or digits','短縮コードは5文字の英数字で入力してください','Le code court doit contenir 5 lettres ou chiffres','Короткий код должен состоять из 5 букв или цифр','El código corto debe tener 5 letras o dígitos','Il codice breve deve contenere 5 lettere o cifre','단축 코드는 영문자 또는 숫자 5자여야 합니다','Kod ringkas mesti mengandungi 5 huruf atau angka','Kode singkat harus berisi 5 huruf atau angka','Mã ngắn phải gồm 5 chữ cái hoặc chữ số','รหัสสั้นต้องมีตัวอักษรหรือตัวเลข 5 ตัว'],
    ['短码无效或会话已结束','短碼無效或工作階段已結束','The short code is invalid or the session has ended','短縮コードが無効か、セッションが終了しています','Le code court est invalide ou la session est terminée','Короткий код недействителен или сеанс завершён','El código corto no es válido o la sesión terminó','Il codice breve non è valido o la sessione è terminata','단축 코드가 잘못되었거나 세션이 종료되었습니다','Kod ringkas tidak sah atau sesi telah tamat','Kode singkat tidak valid atau sesi telah berakhir','Mã ngắn không hợp lệ hoặc phiên đã kết thúc','รหัสสั้นไม่ถูกต้องหรือเซสชันสิ้นสุดแล้ว'],
    ['消息过大','訊息過大','The message is too large','メッセージが大きすぎます','Le message est trop volumineux','Сообщение слишком большое','El mensaje es demasiado grande','Il messaggio è troppo grande','메시지가 너무 큽니다','Mesej terlalu besar','Pesan terlalu besar','Tin nhắn quá lớn','ข้อความมีขนาดใหญ่เกินไป'],
    ['协同编辑内容过大，无法同步','協同編輯內容過大，無法同步','Collaborative content is too large to sync','共同編集の内容が大きすぎて同期できません','Le contenu collaboratif est trop volumineux pour être synchronisé','Совместное содержимое слишком велико для синхронизации','El contenido colaborativo es demasiado grande para sincronizarse','Il contenuto collaborativo è troppo grande per la sincronizzazione','협업 편집 내용이 너무 커서 동기화할 수 없습니다','Kandungan kolaboratif terlalu besar untuk disegerakkan','Konten kolaboratif terlalu besar untuk disinkronkan','Nội dung cộng tác quá lớn để đồng bộ','เนื้อหาการทำงานร่วมกันใหญ่เกินกว่าจะซิงค์'],
    ['协同编辑图片数量已达上限','協同編輯圖片數量已達上限','The collaborative editor has reached its image limit','共同編集の画像数が上限に達しました','L’éditeur collaboratif a atteint sa limite d’images','Достигнут лимит изображений совместного редактора','El editor colaborativo alcanzó el límite de imágenes','L’editor collaborativo ha raggiunto il limite di immagini','협업 편집기의 이미지 한도에 도달했습니다','Editor kolaboratif telah mencapai had imej','Editor kolaboratif telah mencapai batas gambar','Trình chỉnh sửa cộng tác đã đạt giới hạn hình ảnh','ตัวแก้ไขร่วมถึงขีดจำกัดรูปภาพแล้ว'],
    ['放弃发送','放棄傳送','Cancel sending','送信をキャンセル','Annuler l’envoi','Отменить отправку','Cancelar envío','Annulla invio','보내기 취소','Batal hantar','Batalkan pengiriman','Hủy gửi','ยกเลิกการส่ง'],
    ['已放弃发送','已放棄傳送','Sending cancelled','送信をキャンセルしました','Envoi annulé','Отправка отменена','Envío cancelado','Invio annullato','보내기를 취소했습니다','Penghantaran dibatalkan','Pengiriman dibatalkan','Đã hủy gửi','ยกเลิกการส่งแล้ว'],
    ['进入指定的传输隧道中转模式','進入指定的傳輸隧道中轉模式','Relay messages to a specified tunnel','指定したトンネルへの中継モード','Relayer vers un tunnel précis','Пересылать в указанный туннель','Retransmitir a un túnel específico','Inoltra a un tunnel specifico','지정한 터널로 중계','Geganti ke terowong tertentu','Teruskan ke tunnel tertentu','Chuyển tiếp tới đường hầm chỉ định','ส่งต่อไปยังทันเนลที่ระบุ'],
    ['退出当前隧道中转模式','退出目前隧道中轉模式','Leave the current tunnel relay mode','現在のトンネル中継モードを終了','Quitter le mode relais actuel','Выйти из режима пересылки','Salir del modo retransmisión actual','Esci dalla modalità inoltro','현재 터널 중계 모드 종료','Keluar daripada mod geganti','Keluar dari mode relay','Thoát chế độ chuyển tiếp hiện tại','ออกจากโหมดส่งต่อปัจจุบัน']
];

for (const row of SERVER_ROWS) {
    TG[row[0]] = Object.fromEntries(SERVER_LANGUAGES.map((language, index) => [language, row[index + 1]]));
}

function translateExact(text, lang) {
    if (!text || lang === 'zh-Hans') return text;
    const entry = TG[text];
    return entry?.[lang] || entry?.en || text;
}

function translateTelegramText(text, langCode = 'zh-Hans') {
    const lang = normalizeLanguageCode(langCode);
    let translated = translateExact(text, lang);
    if (translated !== text) return translated;
    if (lang === 'zh-Hans') return text;
    let shortMatch = /^当前处于 ([A-Z0-9]{5}) 隧道中转模式$/.exec(text);
    if (shortMatch) return ({
        'zh-Hant': `目前處於 ${shortMatch[1]} 隧道中轉模式`, en: `Relaying to tunnel ${shortMatch[1]}`,
        ja: `${shortMatch[1]} トンネル中継モード`, fr: `Relais vers le tunnel ${shortMatch[1]}`,
        ru: `Ретрансляция в туннель ${shortMatch[1]}`, es: `Retransmitiendo al túnel ${shortMatch[1]}`,
        it: `Inoltro al tunnel ${shortMatch[1]}`, ko: `${shortMatch[1]} 터널 중계 모드`,
        ms: `Menggeganti ke terowong ${shortMatch[1]}`, id: `Meneruskan ke tunnel ${shortMatch[1]}`,
        vi: `Đang chuyển tiếp tới đường hầm ${shortMatch[1]}`, th: `กำลังส่งต่อไปยังทันเนล ${shortMatch[1]}`,
        fa: `در حال انتقال به تونل ${shortMatch[1]}`, km: `កំពុងបញ្ជូនទៅផ្លូវរូង ${shortMatch[1]}`,
        my: `${shortMatch[1]} တန်နယ်သို့ လွှဲပြောင်းနေသည်`
    }[lang] || text);
    let match = /^当前处于 ([A-Z0-9]{5}) 隧道中转模式，直接发送任何内容，将转发到此隧道。$/.exec(text);
    if (match) return ({
        'zh-Hant': `目前處於 ${match[1]} 隧道中轉模式，直接傳送任何內容都會轉發到此隧道。`, en: `Tunnel relay mode is active for ${match[1]}. Anything you send will be forwarded to this tunnel.`, ja: `${match[1]} のトンネル中継モードです。送信した内容はこのトンネルへ転送されます。`, fr: `Le mode relais est actif pour le tunnel ${match[1]}. Tout ce que vous envoyez sera transféré à ce tunnel.`, ru: `Включён режим ретрансляции для туннеля ${match[1]}. Всё отправленное будет переслано туда.`, es: `Modo retransmisión activo para el túnel ${match[1]}. Todo lo que envíes se reenviará a este túnel.`, it: `Modalità inoltro attiva per il tunnel ${match[1]}. Tutto ciò che invii sarà inoltrato a questo tunnel.`, fa: `حالت رله برای تونل ${match[1]} فعال است. هر چیزی بفرستید به این تونل منتقل می‌شود.`, ko: `${match[1]} 터널 중계 모드입니다. 보내는 모든 내용이 이 터널로 전달됩니다.`, ms: `Mod geganti aktif untuk terowong ${match[1]}. Apa-apa yang dihantar akan dimajukan ke terowong ini.`, id: `Mode relay aktif untuk tunnel ${match[1]}. Apa pun yang Anda kirim akan diteruskan ke tunnel ini.`, vi: `Chế độ chuyển tiếp đang bật cho đường hầm ${match[1]}. Mọi nội dung bạn gửi sẽ được chuyển tiếp vào đó.`, km: `របៀបបញ្ជូនសកម្មសម្រាប់ផ្លូវរូង ${match[1]}។ អ្វីៗដែលអ្នកផ្ញើនឹងត្រូវបញ្ជូនទៅផ្លូវរូងនេះ។`, my: `${match[1]} တန်နယ်အတွက် relay မုဒ် ဖွင့်ထားသည်။ သင်ပို့သမျှကို ထိုတန်နယ်သို့ ပို့မည်။`, th: `โหมดส่งต่อเปิดอยู่สำหรับอุโมงค์ ${match[1]} ทุกอย่างที่ส่งจะถูกส่งต่อเข้าอุโมงค์นี้` }[lang] || text);
    match = /^文件太大，当前 Telegram bot 接收上限是 (\d+)MB。$/.exec(text);
    if (match) return ({ en: `The file is too large. The current Telegram bot receive limit is ${match[1]} MB.`, 'zh-Hant': `檔案太大，目前 Telegram bot 接收上限是 ${match[1]}MB。`, ja: `ファイルが大きすぎます。現在の Telegram bot 受信上限は ${match[1]}MB です。`, fr: `Le fichier est trop volumineux. La limite actuelle du bot Telegram est de ${match[1]} Mo.`, ru: `Файл слишком большой. Текущий лимит Telegram bot: ${match[1]} МБ.`, es: `El archivo es demasiado grande. El límite actual del bot de Telegram es ${match[1]} MB.`, it: `Il file è troppo grande. Il limite attuale del bot Telegram è ${match[1]} MB.`, fa: `فایل بیش از حد بزرگ است. سقف دریافت فعلی ربات تلگرام ${match[1]} مگابایت است.`, ko: `파일이 너무 큽니다. 현재 Telegram bot 수신 한도는 ${match[1]}MB입니다.`, ms: `Fail terlalu besar. Had penerimaan Telegram bot ialah ${match[1]} MB.`, id: `File terlalu besar. Batas penerimaan bot Telegram saat ini ${match[1]} MB.`, vi: `Tệp quá lớn. Giới hạn nhận hiện tại của Telegram bot là ${match[1]} MB.`, km: `ឯកសារធំពេក។ កម្រិតទទួលបច្ចុប្បន្នរបស់ Telegram bot គឺ ${match[1]}MB។`, my: `ဖိုင်ကြီးလွန်းသည်။ လက်ရှိ Telegram bot လက်ခံနိုင်သောကန့်သတ်ချက်မှာ ${match[1]}MB ဖြစ်သည်။`, th: `ไฟล์ใหญ่เกินไป ขีดจำกัดรับของ Telegram bot ตอนนี้คือ ${match[1]}MB` }[lang] || text);
    match = /^已发送到隧道 ([A-Z0-9]{5})(?::|：)?(.*)$/.exec(text);
    if (match) return ({ en: `Sent to tunnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, 'zh-Hant': `已傳送到隧道 ${match[1]}${match[2] ? `：${match[2].trim()}` : '。'}`, ja: `トンネル ${match[1]} に送信しました${match[2] ? `：${match[2].trim()}` : '。'}`, fr: `Envoyé au tunnel ${match[1]}${match[2] ? ` : ${match[2].trim()}` : '.'}`, ru: `Отправлено в туннель ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, es: `Enviado al túnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, it: `Inviato al tunnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, fa: `به تونل ${match[1]} ارسال شد${match[2] ? `: ${match[2].trim()}` : '.'}`, ko: `${match[1]} 터널로 보냈습니다${match[2] ? `: ${match[2].trim()}` : '.'}`, ms: `Dihantar ke terowong ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, id: `Dikirim ke tunnel ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, vi: `Đã gửi tới đường hầm ${match[1]}${match[2] ? `: ${match[2].trim()}` : '.'}`, km: `បានផ្ញើទៅផ្លូវរូង ${match[1]}${match[2] ? `: ${match[2].trim()}` : '។'}`, my: `${match[1]} တန်နယ်သို့ ပို့ပြီးပါပြီ${match[2] ? `: ${match[2].trim()}` : '။'}`, th: `ส่งไปยังอุโมงค์ ${match[1]} แล้ว${match[2] ? `: ${match[2].trim()}` : ''}` }[lang] || text);
    match = /^已将 (\d+) 个媒体文件以合辑发送到隧道 ([A-Z0-9]{5})。$/.exec(text);
    if (match) return ({ en: `Sent ${match[1]} media files as a collection to tunnel ${match[2]}.`, 'zh-Hant': `已將 ${match[1]} 個媒體檔案以合輯傳送到隧道 ${match[2]}。`, ja: `${match[1]} 個のメディアファイルを合輯としてトンネル ${match[2]} に送信しました。`, fr: `${match[1]} fichiers média ont été envoyés comme collection au tunnel ${match[2]}.`, ru: `${match[1]} медиафайлов отправлены подборкой в туннель ${match[2]}.`, es: `Se enviaron ${match[1]} archivos multimedia como colección al túnel ${match[2]}.`, it: `${match[1]} file multimediali inviati come raccolta al tunnel ${match[2]}.`, fa: `${match[1]} فایل رسانه‌ای به‌صورت مجموعه به تونل ${match[2]} ارسال شد.`, ko: `미디어 파일 ${match[1]}개를 모음으로 ${match[2]} 터널에 보냈습니다.`, ms: `${match[1]} fail media dihantar sebagai koleksi ke terowong ${match[2]}.`, id: `${match[1]} file media dikirim sebagai koleksi ke tunnel ${match[2]}.`, vi: `Đã gửi ${match[1]} tệp media dưới dạng bộ sưu tập tới đường hầm ${match[2]}.`, km: `បានផ្ញើឯកសារមេឌៀ ${match[1]} ជាបណ្តុំទៅផ្លូវរូង ${match[2]}។`, my: `မီဒီယာဖိုင် ${match[1]} ခုကို စုစည်းမှုအဖြစ် ${match[2]} တန်နယ်သို့ ပို့ပြီးပါပြီ။`, th: `ส่งไฟล์สื่อ ${match[1]} ไฟล์เป็นชุดไปยังอุโมงค์ ${match[2]} แล้ว` }[lang] || text);
    match = /^以下文件超过 20MB，已拦截，无法通过 Telegram 官方云端 Bot API 转发到隧道：\n([\s\S]+)\n\nTelegram 官方说明：Bot API 的 getFile 目前只能下载不超过 20MB 的文件。\n(https?:\/\/\S+)$/.exec(text);
    if (match) {
        const messages = {
            'zh-Hant': ['以下檔案超過 20MB，已攔截，無法透過 Telegram 官方雲端 Bot API 轉發到隧道：', 'Telegram 官方說明：Bot API 的 getFile 目前只能下載不超過 20MB 的檔案。', '……以及另外 {n} 個檔案'],
            en: ['The following files exceed 20 MB and were blocked because the official Telegram cloud Bot API cannot forward them to the tunnel:', 'Telegram documentation: Bot API getFile can currently download files of up to 20 MB only.', '...and {n} more files'],
            ja: ['次のファイルは 20MB を超えるため、Telegram 公式クラウド Bot API からトンネルへ転送できず、ブロックされました：', 'Telegram 公式説明：Bot API の getFile で現在ダウンロードできるファイルは 20MB 以下です。', '…ほか {n} 件'],
            fr: ['Les fichiers suivants dépassent 20 Mo et ont été bloqués, car l’API Bot cloud officielle de Telegram ne peut pas les transférer vers le tunnel :', 'Documentation Telegram : getFile de l’API Bot ne peut actuellement télécharger que des fichiers de 20 Mo maximum.', '…et {n} autres fichiers'],
            ru: ['Следующие файлы превышают 20 МБ и были заблокированы: официальный облачный Telegram Bot API не может переслать их в туннель:', 'Документация Telegram: getFile в Bot API сейчас загружает только файлы размером до 20 МБ.', '…и ещё файлов: {n}'],
            es: ['Los siguientes archivos superan los 20 MB y se bloquearon porque la API Bot oficial en la nube de Telegram no puede reenviarlos al túnel:', 'Documentación de Telegram: getFile de la Bot API solo puede descargar actualmente archivos de hasta 20 MB.', '…y {n} archivos más'],
            it: ['I seguenti file superano 20 MB e sono stati bloccati perché la Bot API cloud ufficiale di Telegram non può inoltrarli al tunnel:', 'Documentazione Telegram: getFile della Bot API può scaricare al momento solo file fino a 20 MB.', '…e altri {n} file'],
            ko: ['다음 파일은 20MB를 초과하여 Telegram 공식 클라우드 Bot API로 터널에 전달할 수 없으므로 차단되었습니다:', 'Telegram 공식 안내: Bot API의 getFile은 현재 20MB 이하 파일만 다운로드할 수 있습니다.', '…외 {n}개 파일'],
            ms: ['Fail berikut melebihi 20 MB dan telah disekat kerana Bot API awan rasmi Telegram tidak dapat memajukannya ke terowong:', 'Dokumentasi Telegram: getFile Bot API kini hanya boleh memuat turun fail sehingga 20 MB.', '…dan {n} fail lagi'],
            id: ['File berikut melebihi 20 MB dan diblokir karena Bot API cloud resmi Telegram tidak dapat meneruskannya ke tunnel:', 'Dokumentasi Telegram: getFile Bot API saat ini hanya dapat mengunduh file hingga 20 MB.', '…dan {n} file lainnya'],
            vi: ['Các tệp sau vượt quá 20 MB và đã bị chặn vì Bot API đám mây chính thức của Telegram không thể chuyển tiếp chúng vào đường hầm:', 'Tài liệu Telegram: getFile của Bot API hiện chỉ tải được tệp tối đa 20 MB.', '…và {n} tệp khác'],
            th: ['ไฟล์ต่อไปนี้มีขนาดเกิน 20 MB และถูกบล็อก เนื่องจาก Bot API แบบคลาวด์อย่างเป็นทางการของ Telegram ไม่สามารถส่งต่อเข้าอุโมงค์ได้:', 'คำอธิบายของ Telegram: ขณะนี้ getFile ของ Bot API ดาวน์โหลดได้เฉพาะไฟล์ไม่เกิน 20 MB', '…และอีก {n} ไฟล์'],
            fa: ['فایل‌های زیر بیش از ۲۰ مگابایت هستند و مسدود شدند، زیرا Bot API ابری رسمی تلگرام نمی‌تواند آن‌ها را به تونل منتقل کند:', 'مستندات تلگرام: getFile در Bot API در حال حاضر فقط فایل‌های حداکثر ۲۰ مگابایت را دانلود می‌کند.', '…و {n} فایل دیگر'],
            km: ['ឯកសារខាងក្រោមលើស 20MB ហើយត្រូវបានទប់ស្កាត់ ព្រោះ Telegram cloud Bot API ផ្លូវការមិនអាចបញ្ជូនទៅផ្លូវរូងបាន៖', 'ឯកសារ Telegram៖ getFile របស់ Bot API បច្ចុប្បន្នអាចទាញយកឯកសារមិនលើស 20MB ប៉ុណ្ណោះ។', '…និងឯកសារ {n} ទៀត'],
            my: ['အောက်ပါဖိုင်များသည် 20MB ကျော်သောကြောင့် ပိတ်ထားပြီး Telegram တရားဝင် cloud Bot API မှ တန်နယ်သို့ မပို့နိုင်ပါ:', 'Telegram လမ်းညွှန်ချက်အရ Bot API ၏ getFile သည် လက်ရှိတွင် 20MB အထိသာ ဒေါင်းလုဒ်လုပ်နိုင်သည်။', '…နောက်ထပ် {n} ဖိုင်']
        };
        const [heading, footer, remainingTemplate] = messages[lang] || messages.en;
        const names = match[1].replace(/……以及另外 (\d+) 个文件$/, (_, count) => remainingTemplate.replace('{n}', count));
        return `${heading}\n${names}\n\n${footer}\n${match[2]}`;
    }
    return text;
}

function matchesTranslatedText(value, sourceText) {
    const actual = String(value || '').trim();
    if (actual === sourceText) return true;
    return ['zh-Hans', ...SERVER_LANGUAGES].some(language => translateTelegramText(sourceText, language) === actual);
}

module.exports = { normalizeLanguageCode, translateTelegramText, matchesTranslatedText };
